// Structured API description of the framework — the single source for
// docs/reference.md, dist/lcars.manifest.json and llms-full.txt
// (generated by scripts/docs.mjs).
//
// Tests enforce that every class in dist/lcars.css is documented here (or
// generated from tokens) and that every class documented here exists.
// Keep descriptions short, literal and imperative: the main readers are AI
// models implementing UIs with this framework.

/** Hard rules for anyone (human or model) building a UI with LCARS. {THEMES} is filled in by the generator. */
export const rules = [
  "Load `lcars.css`; optionally load `lcars.js` with `<script type=\"module\">`. Put `class=\"lcars\"` on `<html>` (or on the wrapper of the LCARS part of a page).",
  "Build pages as `.lcars-app` > one or more `.lcars-frame`. The standard page is a header frame (bottom elbow) followed by a body frame (top elbow) whose `__side` holds navigation and whose `__main` holds content.",
  "Frame parts (`__elbow-top`, `__bar-top`, `__side`, `__main`, `__elbow-bottom`, `__bar-bottom`) must be direct children of `.lcars-frame`. Omit the parts you don't need; never wrap them.",
  "Finish every `__side` with a filler `<div class=\"lcars-block lcars-grow\"></div>` (or put it between items) so the sidebar reaches the elbow.",
  "Bars contain empty `<span class=\"lcars-block\"></span>` segments (weight with `.lcars-grow-N`), optionally a `.lcars-bar__title`, and usually a `.lcars-round-end` cap on the last segment.",
  "Color pieces with classes, never with `background-color`. Use role classes (`lcars-c-primary|secondary|tertiary|accent|muted|alert`) so themes work; use swatch classes (`lcars-c-orange`, …) only for colors that must not change with the theme, and `lcars-c-green` / `lcars-c-alert` for status meaning. For a one-off color set `style=\"--lcars-c: #hex\"`.",
  "Navigation = `<a class=\"lcars-block\">` inside `__side`, current page marked `aria-current=\"page\"`. Actions = `<button class=\"lcars-button\">` in content, or `<button class=\"lcars-block\">` inside sidebars. Toggles use `aria-pressed`, tabs use `role=\"tab\"` + `aria-selected`.",
  "Group content in `.lcars-bracket` cards laid out with `.lcars-grid`; use a `.lcars-bar` with a `.lcars-bar__title` as a section heading.",
  "Forms: `<label class=\"lcars-field\"><span class=\"lcars-label\">Name</span><input class=\"lcars-input\"></label>`. Show errors with `aria-invalid=\"true\"` plus a `.lcars-hint`.",
  "Write labels in normal case; CSS uppercases headings and controls. Keep labels short (1–2 words). Decorative numeric codes such as `04-2291` in elbows/blocks are optional flavor.",
  "Customize by overriding tokens (`--lcars-side`, `--lcars-bar`, `--lcars-gap`, roles, …) on `:root` or an element. Your own unlayered CSS always beats the framework; never use `!important`.",
  "Pick a series look with `data-lcars-theme` on `<html>` (or any element for a scoped look). Theme ids: {THEMES}.",
  "Animate only with `.lcars-pulse` / `.lcars-blink` or `data-lcars-cascade`; they switch off automatically for reduced-motion users.",
  "`lcars.js` is optional and attribute-driven; it must be served over http(s), auto-upgrades elements added later (SPA-safe) and is safe to import during SSR.",
];

/** Frequent errors, with the fix. */
export const mistakes = [
  ["Wrapping frame parts in extra `<div>`s or placing them outside `.lcars-frame`", "Make every `lcars-frame__*` element a direct child of its `.lcars-frame`."],
  ["`style=\"background: #f90\"` on a block, button or elbow", "`class=\"lcars-c-primary\"`, or `style=\"--lcars-c: #f90\"`."],
  ["Only swatch classes (`lcars-c-orange`) everywhere, so theme switching changes nothing", "Use role classes (`lcars-c-primary`, `-secondary`, `-tertiary`, `-accent`) for chrome."],
  ["Sidebar stops short of the bottom elbow", "Add `<div class=\"lcars-block lcars-grow\"></div>` to `__side`."],
  ["`.lcars-button` pills stacked in a sidebar", "Sidebar items are rectangles: use `.lcars-block` (as `<a>` or `<button>`)."],
  ["Paragraphs, inputs or large text inside a bar", "Bars are one `--lcars-bar` tall: put only segments and one short `.lcars-bar__title` in them."],
  ["`<div class=\"lcars-block\" onclick=…>` for actions", "Use `<button class=\"lcars-block\">` or `<a class=\"lcars-block\" href>` so it is focusable and gets hover/active states."],
  ["Meter width set in percent (`style=\"width: 70%\"`)", "`style=\"--lcars-value: .7\"` (0–1) or `aria-valuenow` with `lcars.js`."],
  ["Hand-written CSS for gaps, radii or fonts", "Override the matching token (`--lcars-gap`, `--lcars-inner-radius`, `--lcars-font`)."],
  ["Nesting one `.lcars-app` inside another", "Use a single `.lcars-app` per page; nest `.lcars-frame`s inside `__main` instead."],
  ["Opening a page that loads `lcars.js` from `file://`", "Serve it over http (`npm run dev`, any static server)."],
];

/** "I need … → use …" lookup. */
export const decisions = [
  ["A full-page app layout", "`.lcars-app` with a header frame and a body frame (recipe: app-shell)"],
  ["LCARS chrome on top of an existing app", "A single header `.lcars-frame` (recipe: header-only)"],
  ["Primary navigation", "`<a class=\"lcars-block\">` items in `.lcars-frame__side` (recipe: sidebar-nav)"],
  ["A card / panel", "`.lcars-bracket`, or a nested `.lcars-frame` with both elbows for a heavier panel"],
  ["KPIs / stats", "`.lcars-bracket` + `.lcars-readout` and `.lcars-meter` (recipe: dashboard-tiles)"],
  ["A section heading", "`.lcars-bar` containing a `.lcars-bar__title` (recipe: section-heading)"],
  ["Tabs or a segmented control", "`.lcars-cluster` of `.lcars-button--sm` with `role=\"tab\"`/`aria-selected` (recipe: tabs)"],
  ["A modal", "`<dialog class=\"lcars-dialog\">` wrapping a bracket or frame (recipe: dialog)"],
  ["Tabular data", "`.lcars-table` with `.lcars-num` numeric cells and `.lcars-pill` statuses (recipe: data-table)"],
  ["A form", "`.lcars-field` + `.lcars-input` / `.lcars-check` / `.lcars-switch` / `.lcars-range` (recipe: form)"],
  ["Status tag", "`.lcars-pill` with `lcars-c-green` / `lcars-c-alert` / `lcars-c-muted`"],
  ["Decorative number field", "`<div class=\"lcars-data\" data-lcars-cascade=\"48\"></div>`"],
  ["Live clock or stardate", "`<span data-lcars-clock></span>`, `<span data-lcars-stardate></span>`"],
];

/**
 * Components. `classes` maps each class to its description; `__` marks a
 * part and `--` a modifier. `vars` are per-component custom properties.
 */
export const components = [
  {
    id: "scope",
    name: "Page scope",
    category: "Foundation",
    summary: "Opt-in page styles: black background, LCARS font, text color, heading/link/code styles. Components work without it.",
    elements: "<html> (whole page) or any wrapper element",
    classes: { lcars: "Applies page-level LCARS typography and background to this element and its descendants." },
    example: `<html lang="en" class="lcars">`,
  },
  {
    id: "app",
    name: "App shell",
    category: "Layout",
    summary: "Full-viewport vertical stack of frames; the last child grows to fill the screen.",
    elements: "<div>",
    classes: { "lcars-app": "Full-height column with gaps between frames. One per page." },
    vars: { "--lcars-app-padding": "Outer padding (default clamp(0.5rem, 1.5vw, 1.25rem))." },
    example: `<div class="lcars-app">
  <header class="lcars-frame">…</header>
  <div class="lcars-frame">…</div>
</div>`,
  },
  {
    id: "frame",
    name: "Frame",
    category: "Layout",
    summary: "The sidebar + elbow + bar construction that defines LCARS. A 2-column grid; every part is optional. Header frame = bottom parts only; body frame = top parts only; panel = both.",
    elements: "<section>, <header>, <div>",
    colorDefault: "primary (elbows inherit the frame's --lcars-c)",
    classes: {
      "lcars-frame": "Grid container. Its --lcars-c colors both elbows unless an elbow has its own color class.",
      "lcars-frame--right": "Mirror: sidebar and elbows on the right.",
      "lcars-frame__elbow-top": "Top corner piece (outer curve top-left) with arm and inner fillet drawn automatically. Optional short label sits bottom-right. May be <div>, <a> or <button>.",
      "lcars-frame__elbow-bottom": "Bottom corner piece (outer curve bottom-left). Optional label sits top-right.",
      "lcars-frame__bar-top": "Bar next to the top elbow; behaves like .lcars-bar.",
      "lcars-frame__bar-bottom": "Bar next to the bottom elbow; behaves like .lcars-bar.",
      "lcars-frame__side": "Vertical stack of .lcars-block items between the elbows. Add a .lcars-grow block as filler.",
      "lcars-frame__main": "Content area beside the sidebar.",
    },
    vars: {
      "--lcars-side": "Sidebar width.",
      "--lcars-bar": "Bar thickness.",
      "--lcars-elbow-height": "Minimum elbow height.",
      "--lcars-elbow-reach": "Length of the elbow arm past the sidebar.",
      "--lcars-elbow-rx": "Horizontal radius of the outer curve.",
      "--lcars-inner-radius": "Radius of the inner fillet.",
      "--lcars-frame-pad": "Padding of __main (default 1rem).",
    },
    a11y: "Use landmark elements: <header> for a header frame, <nav aria-label> for __side navigation, <main> for the page's primary __main.",
    example: `<div class="lcars-frame">
  <div class="lcars-frame__elbow-top">02-4471</div>
  <div class="lcars-frame__bar-top">
    <span class="lcars-block lcars-grow-3"></span>
    <span class="lcars-block lcars-c-secondary lcars-round-end"></span>
  </div>
  <nav class="lcars-frame__side" aria-label="Main">
    <a class="lcars-block lcars-c-accent" href="/" aria-current="page">Home</a>
    <a class="lcars-block lcars-c-tertiary" href="/logs">Logs</a>
    <div class="lcars-block lcars-grow"></div>
  </nav>
  <main class="lcars-frame__main">…</main>
</div>`,
  },
  {
    id: "block",
    name: "Block",
    category: "Components",
    summary: "The basic colored rectangle with its label in the bottom-right corner. Sidebar items, bar segments, swatches, big square buttons.",
    elements: "<div>/<span> (decorative), <a href> (navigation), <button> (action)",
    colorDefault: "primary",
    classes: {
      "lcars-block": "Solid colored slab; label bottom-right; hover/active/focus states when it is an <a>, <button> or <label>.",
      "lcars-block--short": "60% of the normal block height.",
      "lcars-block--tall": "Twice the normal block height.",
      "lcars-block--top": "Label at the top instead of the bottom.",
      "lcars-block--start": "Label at the start (left) instead of the end.",
      "lcars-block--center": "Label centered.",
    },
    vars: { "--lcars-block-height": "Minimum height (default 3.5rem)." },
    states: "aria-current / aria-pressed=\"true\" / aria-selected=\"true\" / .is-active → active color; disabled / aria-disabled=\"true\" → dimmed.",
    example: `<a class="lcars-block lcars-c-secondary" href="/sensors">Sensors</a>
<button class="lcars-block lcars-block--tall lcars-c-alert">Red alert</button>`,
  },
  {
    id: "button",
    name: "Button",
    category: "Components",
    summary: "Pill-shaped control for actions in content areas. Label bottom-right.",
    elements: "<button>, <a href>",
    colorDefault: "primary",
    classes: {
      "lcars-button": "Pill button.",
      "lcars-button--sm": "Small (2rem tall).",
      "lcars-button--lg": "Large (3.75rem tall).",
      "lcars-button--block": "Full width.",
      "lcars-button--center": "Centered label.",
      "lcars-addon": "Black number plate inside a button or block, colored with the parent's --lcars-c.",
    },
    vars: { "--lcars-control": "Height.", "--lcars-button-width": "Minimum width (default 7.5rem)." },
    states: "Same as Block. Shape with .lcars-round-start / .lcars-round-end / .lcars-square.",
    example: `<button class="lcars-button">Engage</button>
<button class="lcars-button lcars-c-secondary lcars-round-end">Scan</button>
<button class="lcars-button lcars-c-accent">Warp <span class="lcars-addon">9</span></button>`,
  },
  {
    id: "bar",
    name: "Bar",
    category: "Components",
    summary: "Horizontal strip of segments separated by thin gaps. Segments share width equally unless weighted.",
    elements: "<div>",
    classes: {
      "lcars-bar": "Flex row, one --lcars-bar tall.",
      "lcars-bar--thin": "0.6rem tall.",
      "lcars-bar--thick": "2.5rem tall.",
      "lcars-bar__title": "Heading text sitting in the bar on the background color (use on h1–h6 or span). Does not stretch.",
      "lcars-bar__fixed": "Stops a segment from stretching; give it a width.",
    },
    example: `<div class="lcars-bar">
  <span class="lcars-block lcars-round-start lcars-bar__fixed" style="width: 3rem"></span>
  <h2 class="lcars-bar__title">Engineering</h2>
  <span class="lcars-block lcars-grow-4"></span>
  <span class="lcars-block lcars-c-secondary lcars-round-end"></span>
</div>`,
  },
  {
    id: "bracket",
    name: "Bracket",
    category: "Components",
    summary: "Content between rounded [ ] brackets — the LCARS card/panel.",
    elements: "<section>, <article>, <div>, <form>",
    colorDefault: "secondary",
    classes: {
      "lcars-bracket": "Card with brackets on both sides.",
      "lcars-bracket--start": "Bracket on the start side only.",
      "lcars-bracket--end": "Bracket on the end side only.",
    },
    vars: { "--lcars-bracket-width": "Bracket thickness (default 0.75rem).", "--lcars-bracket-arm": "Bracket arm length (default 2rem)." },
    example: `<section class="lcars-bracket lcars-c-tertiary">
  <span class="lcars-label">Sector</span>
  <h3>Alpha quadrant</h3>
  <p>No anomalies detected.</p>
</section>`,
  },
  {
    id: "typography",
    name: "Typography",
    category: "Components",
    summary: "Text components that work anywhere (headings, links and code are also styled automatically inside .lcars).",
    classes: {
      "lcars-title": "Display heading, right-aligned, heading color.",
      "lcars-label": "Small uppercase caption in the accent color.",
      "lcars-pill": "Small rounded status tag (tertiary by default).",
      "lcars-pill--outline": "Outlined pill.",
      "lcars-list": "List with block-shaped bullets; color items with .lcars-c-*.",
    },
    example: `<h1 class="lcars-title">Main engineering</h1>
<span class="lcars-label">Status</span>
<span class="lcars-pill lcars-c-green">Nominal</span>
<ul class="lcars-list"><li>Warp core</li><li class="lcars-c-secondary">Impulse</li></ul>`,
  },
  {
    id: "meter",
    name: "Meter",
    category: "Components",
    summary: "Segmented level bar driven by --lcars-value (0–1). With lcars.js, aria-valuenow/min/max drive it automatically.",
    elements: "<div role=\"meter\">",
    colorDefault: "tertiary",
    classes: {
      "lcars-meter": "Horizontal segmented meter.",
      "lcars-meter--solid": "No segment gaps.",
      "lcars-meter--round": "Rounded ends.",
      "lcars-meter--vertical": "Vertical; give the parent a height.",
    },
    vars: { "--lcars-value": "Fill level 0–1.", "--lcars-meter-height": "Thickness (default 1rem).", "--lcars-meter-segment": "Segment pitch (default 0.6rem)." },
    a11y: "Add role=\"meter\", aria-label and aria-valuenow/min/max.",
    example: `<div class="lcars-meter" role="meter" aria-label="Shields"
     aria-valuenow="82" aria-valuemin="0" aria-valuemax="100" style="--lcars-value: .82"></div>`,
  },
  {
    id: "data",
    name: "Data",
    category: "Components",
    summary: "Numeric displays: the dense decorative number field and a key/value readout.",
    classes: {
      "lcars-data": "Grid of numbers in mixed palette colors. Fill it yourself or add data-lcars-cascade=\"N\" (lcars.js) to generate and animate N cells.",
      "lcars-readout": "<dl> of key (accent) / value (right-aligned) pairs.",
    },
    vars: { "--lcars-data-cols": "Number of columns (default 8)." },
    a11y: "lcars.js marks cascades aria-hidden; don't put real data in a cascade.",
    example: `<div class="lcars-data" data-lcars-cascade="48" style="--lcars-data-cols: 6"></div>
<dl class="lcars-readout"><dt>Warp factor</dt><dd>9.2</dd><dt>Heading</dt><dd>127 mark 4</dd></dl>`,
  },
  {
    id: "table",
    name: "Table",
    category: "Components",
    summary: "Data table with colored header rule, row caps and hover highlight.",
    elements: "<table>",
    colorDefault: "tertiary",
    classes: { "lcars-table": "Styled table; add .lcars-num to numeric <th>/<td> for right alignment." },
    example: `<table class="lcars-table">
  <thead><tr><th>Officer</th><th class="lcars-num">Shift</th></tr></thead>
  <tbody><tr><td>Commander</td><td class="lcars-num">0800</td></tr></tbody>
</table>`,
  },
  {
    id: "form",
    name: "Forms",
    category: "Components",
    summary: "Restyled native controls. aria-invalid=\"true\" switches a control to the alert color.",
    colorDefault: "tertiary",
    classes: {
      "lcars-field": "Stack of label, control and hint. Use on <label> (or a <div> with a proper <label for>).",
      "lcars-hint": "Small muted helper / error text under a control.",
      "lcars-input": "<input>, <select> or <textarea>.",
      "lcars-check": "Checkbox or radio (<input type=\"checkbox|radio\">).",
      "lcars-switch": "Checkbox rendered as a toggle switch.",
      "lcars-range": "<input type=\"range\">.",
      "lcars-choice": "<label> wrapping a check/switch and its text.",
    },
    example: `<label class="lcars-field">
  <span class="lcars-label">Destination</span>
  <input class="lcars-input" name="dest" placeholder="Sector 001">
</label>
<label class="lcars-choice"><input class="lcars-switch" type="checkbox" checked> Autopilot</label>`,
  },
  {
    id: "dialog",
    name: "Dialog",
    category: "Components",
    summary: "Styles a native <dialog> as an LCARS modal. Open with dialog.showModal(); close with <form method=\"dialog\">.",
    elements: "<dialog>",
    classes: { "lcars-dialog": "Black modal surface with dark backdrop; put a bracket or frame inside." },
    vars: { "--lcars-dialog-width": "Maximum width (default 40rem)." },
    example: `<dialog class="lcars-dialog" id="confirm">
  <form method="dialog" class="lcars-bracket lcars-c-alert">
    <h3>Confirm self-destruct</h3>
    <button class="lcars-button lcars-c-alert" value="yes">Confirm</button>
  </form>
</dialog>`,
  },
  {
    id: "layout",
    name: "Layout helpers",
    category: "Layout",
    summary: "Small layout primitives. All use --lcars-space for spacing.",
    classes: {
      "lcars-stack": "Vertical flex stack with --lcars-space gaps.",
      "lcars-cluster": "Wrapping horizontal row (button groups, tags).",
      "lcars-split": "Row with items pushed to both ends.",
      "lcars-grid": "Responsive auto-fit grid; min column width --lcars-grid-min.",
      "lcars-span-all": "Grid child spanning every column.",
    },
    vars: { "--lcars-space": "Gap size.", "--lcars-grid-min": "Minimum grid column width (default 16rem)." },
    example: `<div class="lcars-grid" style="--lcars-grid-min: 18rem">
  <section class="lcars-bracket">…</section>
  <section class="lcars-bracket">…</section>
</div>`,
  },
];

/** Utilities that are not generated from the palette. */
export const utilities = [
  {
    group: "Shape",
    classes: {
      "lcars-round": "Fully rounded (pill).",
      "lcars-round-start": "Rounded start (left) side only.",
      "lcars-round-end": "Rounded end (right) side only.",
      "lcars-square": "No rounding.",
    },
  },
  {
    group: "Flex sizing",
    classes: {
      "lcars-grow": "flex-grow: 1 — bar segment weight / sidebar filler.",
      "lcars-grow-0": "flex-grow: 0.",
      "lcars-grow-2": "flex-grow: 2.",
      "lcars-grow-3": "flex-grow: 3.",
      "lcars-grow-4": "flex-grow: 4.",
      "lcars-grow-6": "flex-grow: 6.",
      "lcars-grow-8": "flex-grow: 8.",
    },
  },
  {
    group: "Text",
    classes: {
      "lcars-upper": "Uppercase text.",
      "lcars-num": "Tabular numbers (and right-aligned inside .lcars-table).",
      "lcars-text-start": "text-align: start.",
      "lcars-text-center": "text-align: center.",
      "lcars-text-end": "text-align: end.",
    },
  },
  {
    group: "Motion",
    classes: {
      "lcars-pulse": "Brightness pulse (only without reduced motion).",
      "lcars-blink": "On/off blink (only without reduced motion).",
    },
  },
  {
    group: "Accessibility",
    classes: { "lcars-sr-only": "Visually hidden, still read by screen readers." },
  },
];

/** State hooks that restyle components. */
export const states = [
  ["aria-current (any value but \"false\")", ".lcars-block, .lcars-button", "Active color (--lcars-active)."],
  ["aria-pressed=\"true\" / aria-selected=\"true\" / .is-active", ".lcars-block, .lcars-button", "Active color."],
  ["disabled / aria-disabled=\"true\"", ".lcars-block, .lcars-button, form controls", "Dimmed, not-allowed cursor, no hover."],
  ["aria-invalid=\"true\"", ".lcars-input, .lcars-check, .lcars-switch", "Alert color."],
  ["data-lcars-alert (on an ancestor)", "frame elbows, bar segments, sidebar items", "Pulse (set by LCARS.setAlert)."],
  ["data-lcars-theme=\"id\"", "any element", "Applies a theme to that subtree."],
];

/** Data attributes handled by lcars.js. */
export const attributes = [
  ["data-lcars-clock", "any element", "Live 24h clock HH:MM:SS; value \"hm\" drops seconds."],
  ["data-lcars-stardate", "any element", "Today's stardate as YYYY.DDD."],
  ["data-lcars-cascade=\"N\"", ".lcars-data", "Generates N random readouts and animates them."],
  ["data-lcars-set-theme=\"id\"", "clickable element", "Switches the page theme on click (\"\" = default)."],
  ["data-lcars-theme-select", "<select>", "Fills itself with every theme and switches on change."],
  ["data-lcars-toggle-alert", "clickable element", "Toggles red alert on click."],
  ["data-lcars-sound=\"tap|confirm|deny\"", "ancestor element", "Clicks on interactive descendants beep; \"off\" disables."],
  ["data-lcars-tone=\"tap|confirm|deny\"", "interactive element", "Overrides the beep tone for that element."],
  ["aria-valuenow / -min / -max", ".lcars-meter", "Kept in sync with --lcars-value."],
  ["data-lcars-manual", "<html>", "Disables auto-init; call LCARS.init(el) yourself."],
];

/** Public JS API (import from "lcars/lcars.js" or window.LCARS). */
export const js = [
  ["init(scope = document)", "Upgrade LCARS elements inside scope. Idempotent."],
  ["setTheme(id, el = <html>)", "Apply a theme id (\"\" or null = default). Fires \"lcars:theme\"."],
  ["setAlert(on?, el = <html>)", "Enter/leave red alert; no argument toggles. Restores the previous theme. Fires \"lcars:alert\"."],
  ["beep(tone = \"tap\", { volume })", "Play a synthesized console tone: \"tap\", \"confirm\" or \"deny\"."],
  ["stardate(date = new Date())", "\"YYYY.DDD\" string."],
  ["clock(date = new Date(), { seconds = true })", "\"HH:MM:SS\" string."],
  ["randomReadout(random = Math.random)", "Random LCARS-style number string."],
  ["THEMES", "Array of { id, name, era, note } for every theme."],
];

export const events = [
  ["lcars:theme", "{ theme: string | null }", "Dispatched (bubbling) on the element whose theme changed."],
  ["lcars:alert", "{ active: boolean }", "Dispatched (bubbling) when red alert starts or ends."],
];
