// Generates the machine- and human-readable documentation from the sources
// of truth, so docs cannot drift from the code:
//
//   src/meta/api.mjs     component/utility/JS descriptions, rules, mistakes
//   src/css/tokens.css   token names, defaults and descriptions
//   src/css/themes.css   theme ids and per-theme geometry overrides
//   src/js/lcars.js      THEMES catalogue (names, eras)
//   src/recipes/*.html   copy-paste patterns
//
// Outputs (paths relative to the repo root):
//   docs/reference.md            complete API reference
//   docs/recipes.md              every recipe with its markup
//   examples/recipes/*.html      each recipe as a live page + an index
//   dist/lcars.manifest.json     machine-readable API
//   llms.txt                     llmstxt.org index
//   llms-full.txt                everything an AI model needs, in one file
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const read = (...p) => readFileSync(join(ROOT, ...p), "utf8");
const pkg = JSON.parse(read("package.json"));
const REPO = pkg.repository.url.replace(/^.*github\.com\//, "").replace(/\.git$/, "");
const BRANCH = "master";
const RAW = `https://raw.githubusercontent.com/${REPO}/${BRANCH}`;
const CDN = `https://cdn.jsdelivr.net/gh/${REPO}@${BRANCH}`;
const GENERATED = "Generated by scripts/docs.mjs — edit src/meta/api.mjs, src/css/*.css or src/recipes/ instead.";

export const ROLE_NAMES = ["primary", "secondary", "tertiary", "accent", "muted", "alert", "active"];

/* ── Parsers ─────────────────────────────────────────────── */

/** Tokens from tokens.css: [{ name, value, description, group }]. */
export function parseTokens() {
  const tokens = [];
  let group = "";
  for (const line of read("src", "css", "tokens.css").split("\n")) {
    const heading = line.match(/\/\*\s*──\s*(.+?)\s*─/);
    if (heading) group = heading[1];
    const decl = line.match(/^\s*(--lcars-[a-z0-9-]+):\s*(.+?);\s*(?:\/\*\s*(.*?)\s*\*\/)?\s*$/);
    if (decl) tokens.push({ name: decl[1], value: decl[2], description: decl[3] ?? "", group });
  }
  return tokens;
}

export const paletteTokens = () => parseTokens().filter((t) => t.group === "Palette");

/** Themes: THEMES metadata merged with the variables each block sets. */
export async function parseThemes() {
  const { THEMES } = await import(new URL("../src/js/lcars.js", import.meta.url));
  const css = read("src", "css", "themes.css");
  const blocks = new Map(
    [...css.matchAll(/\[data-lcars-theme="([^"]+)"\]\s*\{([^}]*)\}/g)].map(([, id, body]) => [
      id,
      Object.fromEntries([...body.matchAll(/(--lcars-[a-z0-9-]+):\s*([^;]+);/g)].map(([, k, v]) => [k, v.trim()])),
    ]),
  );
  const palette = new Set(paletteTokens().map((t) => t.name));
  const roleVars = new Set(Object.keys(blocks.get("tng") ?? {}));
  return THEMES.map((t) => {
    const vars = blocks.get(t.id) ?? {};
    const pick = (fn) => Object.fromEntries(Object.entries(vars).filter(([k]) => fn(k)));
    return {
      ...t,
      roles: pick((k) => roleVars.has(k)),
      geometry: pick((k) => !roleVars.has(k) && !palette.has(k)),
      remapsSwatches: Object.keys(vars).some((k) => palette.has(k)),
    };
  });
}

/** Recipes from src/recipes/*.html with their front-matter comment. */
export function parseRecipes() {
  return readdirSync(join(ROOT, "src", "recipes"))
    .filter((f) => f.endsWith(".html"))
    .sort()
    .map((file) => {
      const text = read("src", "recipes", file);
      const [, head, body] = text.match(/^<!--([\s\S]*?)-->\s*([\s\S]*)$/) ?? [];
      if (!head) throw new Error(`${file}: missing front-matter comment`);
      const meta = Object.fromEntries(
        [...head.matchAll(/^\s*([a-z-]+):\s*(.+)$/gm)].map(([, k, v]) => [k, v.trim()]),
      );
      const id = file.replace(/^\d+-/, "").replace(/\.html$/, "");
      return { id, file, title: meta.title, summary: meta.summary, page: meta.page === "true", markup: body.trimEnd() };
    });
}

/* ── Class inventory ─────────────────────────────────────── */

export async function loadApi() {
  const api = await import(new URL("../src/meta/api.mjs", import.meta.url));
  const ids = (await parseThemes()).map((t, i) => (i === 0 ? `${t.id} (default)` : t.id)).join(", ");
  return { ...api, rules: api.rules.map((r) => r.replace("{THEMES}", ids)) };
}

/** Every documented class: [{ class, description, source, kind }]. */
export async function documentedClasses() {
  const api = await loadApi();
  const out = [];
  const kind = (cls) => (cls.includes("__") ? "part" : cls.includes("--") ? "modifier" : "block");
  for (const c of api.components) {
    for (const [cls, description] of Object.entries(c.classes)) out.push({ class: cls, description, source: c.id, kind: kind(cls) });
  }
  for (const u of api.utilities) {
    for (const [cls, description] of Object.entries(u.classes)) out.push({ class: cls, description, source: `utility:${u.group}`, kind: "utility" });
  }
  const colors = [...ROLE_NAMES.map((r) => [r, `role --lcars-${r}`]), ...paletteTokens().map((t) => [t.name.slice(8), `swatch ${t.value}`])];
  for (const [name, what] of colors) {
    out.push({ class: `lcars-c-${name}`, description: `Sets --lcars-c to the ${what}.`, source: "utility:Color", kind: "utility" });
    out.push({ class: `lcars-text-${name}`, description: `Text color: the ${what}.`, source: "utility:Color", kind: "utility" });
  }
  out.push({ class: "lcars-text-fg", description: "Text color: --lcars-fg (body text).", source: "utility:Color", kind: "utility" });
  return out;
}

/* ── Markdown helpers ────────────────────────────────────── */

const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
const table = (head, rows) =>
  [`| ${head.join(" | ")} |`, `| ${head.map(() => "---").join(" | ")} |`, ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`)].join("\n");
const code = (lang, s) => "```" + lang + "\n" + s.trim() + "\n```";

/* ── Documents ───────────────────────────────────────────── */

function setupSection() {
  return `## Setup

\`\`\`html
<!doctype html>
<html lang="en" class="lcars" data-lcars-theme="tng">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="${CDN}/dist/lcars.min.css">
  <script type="module" src="${CDN}/dist/lcars.js"></script> <!-- optional -->
</head>
<body>
  <!-- see recipe "app-shell" -->
</body>
</html>
\`\`\`

npm: \`npm install github:${REPO}\`, then \`import "lcars/lcars.css"\` and optionally \`import "lcars/lcars.js"\`.
Files: \`dist/lcars.css\` (readable), \`dist/lcars.min.css\`, \`dist/lcars.js\` (ES module), \`dist/fonts/\` (keep next to the CSS), \`dist/lcars.manifest.json\` (this API as JSON).`;
}

async function referenceMd() {
  const api = await loadApi();
  const tokens = parseTokens();
  const themes = await parseThemes();
  const recipes = parseRecipes();
  const out = [];

  out.push(`# LCARS — API reference (v${pkg.version})

<!-- ${GENERATED} -->

LCARS is a framework-agnostic CSS design system for building Star Trek LCARS-style interfaces. It is plain HTML classes + CSS custom properties (all inside \`@layer lcars.*\`), plus an optional dependency-free ES module (\`lcars.js\`) for clocks, animated data, theme switching and sounds. It works with any stack that outputs HTML (static, React, Vue, Svelte, server templates).

Read **Rules** and **Common mistakes** first; copy structure from **Recipes** (docs/recipes.md).`);

  out.push(setupSection());

  out.push(`## Rules\n\n${api.rules.map((r, i) => `${i + 1}. ${r}`).join("\n")}`);
  out.push(`## Common mistakes\n\n${table(["Don't", "Do"], api.mistakes)}`);
  out.push(`## Which component do I need?\n\n${table(["Need", "Use"], api.decisions)}`);

  out.push(`## Color model

Every colored piece (block, button, elbow, bar segment, bracket, meter, pill, table, input) paints itself with \`var(--lcars-c)\` and sets a default for it. Change the color with a class:

- \`lcars-c-{role}\` — ${ROLE_NAMES.join(", ")}. **Themeable: prefer these.**
- \`lcars-c-{swatch}\` — ${paletteTokens().map((t) => t.name.slice(8)).join(", ")}. Fixed colors (only red-alert remaps them).
- \`style="--lcars-c: #hex"\` — one-off color.
- \`lcars-text-{role|swatch|fg}\` sets \`color\` instead.

Text on colored pieces uses \`--lcars-on-c\` (black). State attributes (\`aria-current\`, \`aria-pressed\`, \`aria-invalid\`, …) override color classes.`);

  out.push("## Components");
  for (const c of api.components) {
    const parts = [`### ${c.name} — \`${Object.keys(c.classes)[0]}\``, c.summary];
    const meta = [];
    if (c.elements) meta.push(`**Use on:** ${c.elements}`);
    if (c.colorDefault) meta.push(`**Default color:** ${c.colorDefault}`);
    if (meta.length) parts.push(meta.join(" · "));
    parts.push(table(["Class", "Description"], Object.entries(c.classes).map(([k, v]) => [`\`${k}\``, v])));
    if (c.vars) parts.push(table(["Custom property", "Description"], Object.entries(c.vars).map(([k, v]) => [`\`${k}\``, v])));
    if (c.states) parts.push(`**States:** ${c.states}`);
    if (c.a11y) parts.push(`**Accessibility:** ${c.a11y}`);
    if (c.example) parts.push(code("html", c.example));
    out.push(parts.join("\n\n"));
  }

  out.push(`## Utilities

**Color:** \`lcars-c-*\` and \`lcars-text-*\` for every role and swatch (see Color model).

${api.utilities.map((u) => `**${u.group}**\n\n${table(["Class", "Description"], Object.entries(u.classes).map(([k, v]) => [`\`${k}\``, v]))}`).join("\n\n")}`);

  out.push(`## States\n\n${table(["Attribute / class", "Applies to", "Effect"], api.states)}`);

  const groups = [...new Set(tokens.map((t) => t.group))];
  out.push(`## Tokens

Override on \`:root\` for the whole app, or on any element for a subtree.

${groups
  .map((g) =>
    g === "Palette"
      ? `**Palette** (fixed swatches)\n\n${table(["Token", "Value", "Class"], tokens.filter((t) => t.group === g).map((t) => [`\`${t.name}\``, t.value, `\`lcars-c-${t.name.slice(8)}\``]))}`
      : `**${g}**\n\n${table(["Token", "Default", "Description"], tokens.filter((t) => t.group === g).map((t) => [`\`${t.name}\``, `\`${t.value}\``, t.description]))}`,
  )
  .join("\n\n")}`);

  out.push(`## Themes

Set \`data-lcars-theme="id"\` on \`<html>\` or any element. No attribute = \`tng\`. Themes are fan interpretations of each series' look; some also change geometry.

${table(
  ["id", "Series", "Era", "Character", "Geometry overrides"],
  themes.map((t) => [
    `\`${t.id}\``,
    t.name,
    t.era,
    t.note + (t.remapsSwatches ? " (also remaps all swatches)" : ""),
    Object.entries(t.geometry).map(([k, v]) => `${k}: ${v}`).join("; ") || "—",
  ]),
)}

Custom theme: copy any block from \`src/css/themes.css\` under a new id and define every role (${Object.keys(themes[0].roles).map((k) => `\`${k}\``).join(", ")}).`);

  out.push(`## JavaScript (optional \`lcars.js\`)

Auto-initialises on load and upgrades elements added later. \`<html data-lcars-manual>\` disables auto-init.

**Attributes**

${table(["Attribute", "On", "Effect"], api.attributes.map(([a, on, e]) => [`\`${a}\``, on, e]))}

**API** (\`import LCARS, { setTheme } from "lcars/lcars.js"\` or \`window.LCARS\`)

${table(["Member", "Description"], api.js.map(([a, d]) => [`\`${a}\``, d]))}

**Events**

${table(["Event", "detail", "When"], api.events.map(([e, d, w]) => [`\`${e}\``, `\`${d}\``, w]))}`);

  out.push(`## Recipes

Full markup in docs/recipes.md; live pages in examples/recipes/.

${table(["Recipe", "Use for"], recipes.map((r) => [`\`${r.id}\``, r.summary]))}`);

  return out.join("\n\n") + "\n";
}

function recipesMd() {
  const recipes = parseRecipes();
  return `# LCARS — Recipes

<!-- ${GENERATED} -->

Copy-paste patterns built only from framework classes. Each is rendered live at \`examples/recipes/<id>.html\`. Recipes marked *page* are full \`<body>\` contents; the rest are fragments for a frame's \`__main\`. Colors use theme roles, so every recipe follows \`data-lcars-theme\`.

${recipes
  .map((r) => `## ${r.title} (\`${r.id}\`${r.page ? ", page" : ""})\n\n${r.summary}\n\n${code("html", r.markup)}`)
  .join("\n\n")}
`;
}

function recipePage(r) {
  return `<!doctype html>
<!-- ${GENERATED} Source: src/recipes/${r.file} -->
<html lang="en" class="lcars">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LCARS recipe: ${r.title}</title>
  <link rel="stylesheet" href="../../dist/lcars.css">
  <script type="module" src="../../dist/lcars.js"></script>
</head>
<body>
${r.page ? r.markup : `<div style="padding: clamp(1rem, 3vw, 2rem)">\n${r.markup}\n</div>`}
</body>
</html>
`;
}

function recipeIndex() {
  const recipes = parseRecipes();
  return `<!doctype html>
<!-- ${GENERATED} -->
<html lang="en" class="lcars">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LCARS Recipes</title>
  <link rel="stylesheet" href="../../dist/lcars.css">
  <script type="module" src="../../dist/lcars.js"></script>
</head>
<body>
  <div class="lcars-app">
    <div class="lcars-frame">
      <div class="lcars-frame__elbow-top">Recipes</div>
      <div class="lcars-frame__bar-top">
        <span class="lcars-block lcars-grow-3"></span>
        <span class="lcars-block lcars-c-secondary lcars-round-end"></span>
      </div>
      <nav class="lcars-frame__side" aria-label="Examples">
        <a class="lcars-block lcars-c-accent" href="../index.html">Library</a>
        <a class="lcars-block lcars-c-tertiary" href="../dashboard.html">Dashboard</a>
        <div class="lcars-block lcars-grow"></div>
      </nav>
      <main class="lcars-frame__main lcars-stack">
        <div class="lcars-split">
          <h1 class="lcars-title" style="text-align: start">Recipes</h1>
          <select class="lcars-input" data-lcars-theme-select aria-label="Theme" style="width: min(17rem, 100%)"></select>
        </div>
        <div class="lcars-grid" style="--lcars-grid-min: 24rem">
${recipes
  .map(
    (r) => `          <section class="lcars-bracket lcars-c-tertiary">
            <h2 style="font-size: var(--lcars-text-xl)"><a href="${r.id}.html">${r.title}</a></h2>
            <p>${r.summary.replace(/</g, "&lt;")}</p>
            <iframe src="${r.id}.html" title="${r.title} preview" loading="lazy" style="width: 100%; height: 22rem; border: 0; background: var(--lcars-bg)"></iframe>
          </section>`,
  )
  .join("\n")}
        </div>
      </main>
    </div>
  </div>
</body>
</html>
`;
}

async function manifest() {
  const api = await loadApi();
  return JSON.stringify(
    {
      $comment: GENERATED,
      name: pkg.name,
      version: pkg.version,
      description: pkg.description,
      files: {
        css: "dist/lcars.css",
        cssMin: "dist/lcars.min.css",
        js: "dist/lcars.js",
        fonts: "dist/fonts/",
        cdn: { css: `${CDN}/dist/lcars.min.css`, js: `${CDN}/dist/lcars.js` },
        reference: "docs/reference.md",
        recipes: "docs/recipes.md",
      },
      rules: api.rules,
      mistakes: api.mistakes.map(([dont, fix]) => ({ dont, do: fix })),
      decisions: api.decisions.map(([need, use]) => ({ need, use })),
      components: api.components,
      utilities: api.utilities,
      classes: await documentedClasses(),
      states: api.states.map(([when, appliesTo, effect]) => ({ when, appliesTo, effect })),
      tokens: parseTokens(),
      themes: await parseThemes(),
      attributes: api.attributes.map(([attribute, on, effect]) => ({ attribute, on, effect })),
      js: api.js.map(([member, description]) => ({ member, description })),
      events: api.events.map(([event, detail, when]) => ({ event, detail, when })),
      recipes: parseRecipes().map(({ id, title, summary, page, file }) => ({
        id, title, summary, page, source: `src/recipes/${file}`, live: `examples/recipes/${id}.html`,
      })),
    },
    null,
    2,
  ) + "\n";
}

async function llmsTxt() {
  const api = await loadApi();
  const recipes = parseRecipes();
  return `# LCARS

> Framework-agnostic LCARS (Star Trek computer interface) design system for web apps: plain CSS classes and design tokens in cascade layers, themes for every Star Trek series, and an optional dependency-free ES module. Works with any stack that outputs HTML.

Essentials:
- Load \`${CDN}/dist/lcars.min.css\` (and optionally \`${CDN}/dist/lcars.js\` as a module); put \`class="lcars"\` on <html>.
- Page = \`.lcars-app\` > \`.lcars-frame\` (parts: \`__elbow-top\`, \`__bar-top\`, \`__side\`, \`__main\`, \`__elbow-bottom\`, \`__bar-bottom\`, all direct children).
- Color pieces with \`lcars-c-{primary|secondary|tertiary|accent|muted|alert}\` so themes work; themes via \`data-lcars-theme\` = ${(await parseThemes()).map((t) => t.id).join(", ")}.
- ${api.components.length} components, ${(await documentedClasses()).length} classes, ${parseTokens().length} tokens; every one is listed in the reference and manifest.

## Docs

- [Full context (single file)](${RAW}/llms-full.txt): rules, mistakes, complete reference and all recipes — load this when implementing.
- [API reference](${RAW}/docs/reference.md): rules, components, utilities, tokens, themes, JS.
- [Recipes](${RAW}/docs/recipes.md): copy-paste markup for ${recipes.map((r) => r.id).join(", ")}.
- [Manifest](${RAW}/dist/lcars.manifest.json): the same API as JSON (classes, tokens, themes, attributes).

## Examples

- [Component library](${RAW}/examples/index.html): every component with its source.
- [Operations dashboard](${RAW}/examples/dashboard.html): a complete app.
- [Starter](${RAW}/examples/starter.html): minimal page to copy.

## Optional

- [README](${RAW}/README.md): overview, install, development.
- [Source CSS](https://github.com/${REPO}/tree/${BRANCH}/src/css): tokens.css, themes.css, frame.css, components/.
`;
}

/** Map of repo-relative path → generated contents. */
export async function generateDocs() {
  const reference = await referenceMd();
  const recipes = recipesMd();
  const files = new Map([
    ["docs/reference.md", reference],
    ["docs/recipes.md", recipes],
    ["dist/lcars.manifest.json", await manifest()],
    ["llms.txt", await llmsTxt()],
    [
      "llms-full.txt",
      `# LCARS — full context for AI models\n\n<!-- ${GENERATED} -->\n\nThis file is docs/reference.md followed by docs/recipes.md.\n\n${reference.replace(/^# .*\n/, "")}\n\n---\n\n${recipes}`,
    ],
    ["examples/recipes/index.html", recipeIndex()],
  ]);
  for (const r of parseRecipes()) files.set(`examples/recipes/${r.id}.html`, recipePage(r));
  return files;
}
